Web/Controllers/AutorController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Web.Utils;

namespace Web.Controllers
{
    public class AutorController : Controller
    {
        // GET: Autor
        public ActionResult Index()
        {
            IEnumerable<Autor> lista = null;
            try
            {
                IServiceAutor _ServiceAutor = new ServiceAutor();
                lista = _ServiceAutor.GetAutors();
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }
            return View(lista);

        }

        // GET: Autor/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Autor/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Autor/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Autor/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Autor/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Autor/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Autor/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    @RenderSection("styles", required: false)
    
</head>
<body>
    @Html.Partial("_Menu")
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ISW-711</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@

    <script src="~/Scripts/bootstrap.bundle.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

Web/Views/Shared/_Menu.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        @Html.ActionLink("Librería", "Index", "Home", null, new { @class = "navbar-brand" })

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="#">
                        Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Mantenimientos</a>
                    <div class="dropdown-menu">
                        @*Enlace a la lista de autores*@
                        @Html.ActionLink("Autores", "Index", "Autor",
               null, new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Libro", "IndexAdmin", "Libro", null, new { @class = "dropdown-item" })
                        <div class="dropdown-divider"></div>
                        @Html.ActionLink("Orden", "IndexAdmin", "Orden", null, new { @class = "dropdown-item" })

                    </div>
                </li>
                @* Texto Usuario, Accion, Controlador*@
                <li>
                    @Html.ActionLink("Acerca de", "About", "Home",
               null, new { @class = "nav-link" })
                </li>
                <li>@Html.ActionLink("Contacto", "Contact", "Home", null, new { @class = "nav-link" })</li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" 
                       href="#" role="button" aria-haspopup="true" 
                       aria-expanded="false"><i class="fa-solid fa-user"></i> Perfil</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item"
                           @*Accion, Controlador*@
                           href="@Url.Action("Index","Login")">
                            <i class="fa-solid fa-user-plus"></i>
                            Login
                        </a>
                        <a class="dropdown-item"
                           href="@Url.Action("Logout","Login")">
                            <i class="fa-solid fa-right-from-bracket"></i>
                            Logout
                        </a>
                    </div>
                </li>
            </ul>

        </div>
    </div>
</nav>